[project]
name = "transaction-network-analyzer"
version = "0.0.1"
description = "Network-based fraud ring detection for P2P marketplace transactions"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "networkx>=3.4",
    "pandas>=2.2",
    "matplotlib>=3.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tna"]

[dependency-groups]
dev = [
    "ty",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pytest-local-badge",
    "ruff"
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 120
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = [
    "INP001"  # File `docs/conf.py` is part of an implicit namespace package. Add an `__init__.py`.
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ty.environment]
python-version = "3.14"

[tool.ty.src]
include = ["src", "tests"]

[tool.ty.analysis]
allowed-unresolved-imports = []

[tool.ty.rules]
all = "warn"
unresolved-import = "ignore"

[tool.pytest.ini_options]
addopts = """
--cov=src/ \
--cov-report html:tests/report/coverage-html \
--cov-report xml:tests/report/coverage.xml \
--local-badge-output-dir tests/report/ \
--local-badge-generate cov status requires-python version \
--local-badge-package=transaction-network-analyzer \
--ignore=docs/
--cov-fail-under=75 \
-v
"""
testpaths = ["tests"]
pythonpath = ["src"]

[tool.coverage.run]
source = ["src"]
data_file = "tests/report/.coverage"
omit = [
    "*/tests/*",
    "*/venv/*",
    "*/.venv/*",
    "*/migrations/*",
    "*/settings/*",
    "manage.py",
    "*/conftest.py"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "class .*\\(Protocol\\):",
    "@(abc\\.)?abstractmethod"
]
